### ISSUE TITLE
feature request: build both sim and ios 

### ISSUE THREAD

**Issue by chml** [swiftyfinch/Rugby#1]
And this open source? I'd love to contribute

**Comment by swiftyfinch** [comment]
@chml Hi! No, I'm not ready now.
But I'm going to open source in the future.

**Comment by swiftyfinch** [comment]
I decided to close this issue because the main goal of 🏈 Rugby is optimization.
If we build both SDKs, it will take 2x longer. But you need only one at the present time.
You can switch between SDKs faster enough and all cache will be saved for each SDKs appropriately.

@chml Sorry, I'm not going to add this feature in nearest future.

**Comment by swiftyfinch** [comment]
@chml #84
