### ISSUE TITLE
🐛 Build failed because of duplicate symbols if we  use `--force_load` in xcconfig

### ISSUE THREAD

**Issue by blastmann** [swiftyfinch/Rugby#125]
## To Reproduce

1. Create a empty project
2. Integrate a pod will use `-force_load` in `OTHER_LDFLAGS`
3. Run `rugby` and build 
4. Build failed because of duplicate symbols

## Expected behavior

It should build successfully.

## Screenshots

![image](https://user-images.githubusercontent.com/2032369/151579431-18e406e9-2bfb-4173-be00-a88ce7727321.png)

## Environment (please complete the following information):
 - Version 1.15.0
 - Logs (use `rugby doctor`)
 - Here is a sample project: [iOSApp.zip](https://github.com/swiftyfinch/Rugby/files/7959986/iOSApp.zip)

## Additional context

I found that Xcode treats the relative path and absolute path as different. Rugby should use absolute path in xcconfig to replace the original one. e.g:

```
// original 
OTHER_LDFLAGS = $(inherited) -ObjC -l"c++" -l"hippy" -force_load ${PODS_CONFIGURATION_BUILD_DIR}/hippy/libhippy.a

// replaced and build failed
OTHER_LDFLAGS = $(inherited) -ObjC -l"c++" -l"hippy" -force_load ${PODS_ROOT}/../.rugby/build/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}/hippy/libhippy.a

// replaced and build successfullly
OTHER_LDFLAGS = $(inherited) -ObjC -l"c++" -l"hippy" -force_load ${SRC_ROOT}/.rugby/build/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}/hippy/libhippy.a
```

**Comment by swiftyfinch** [comment]
@batman Hello! Thank you for details. As I can see you already have the solution.
I wonder if you ready to make a pull request? Let me know

**Comment by blastmann** [comment]
Sure, I will try to make a PR later.

**Comment by swiftyfinch** [comment]
As I understand Xcode considers these are different paths:
```shell
duplicate symbol '_OBJC_CLASS_$_PodsDummy_hippy' in:
    ~/Developer/Repos/SwiftyFinch/Rugby/TestProject/TestProject/../Pods/.rugby/build/Debug-iphonesimulator/hippy/libhippy.a (hippy-dummy.o)
    ~/Developer/Repos/SwiftyFinch/Rugby/TestProject/Pods/.rugby/build/Debug-iphonesimulator/hippy/libhippy.a (hippy-dummy.o)
```
But they are the same, so we get `duplicate symbol` error while building.

I checked out your pull request and there is a problem with `$SRCROOT`.
`$SRCROOT` can be like this `$GIT_ROOT/.` or like this `$GIT_ROOT/$PROJECT_DIR/.`.

I see only two solutions:
1. We can add a new variable to the main Xcode project from the workspace. Something like `$RUGBY_PATH`. But I don't like this solution, because it will become dependency in such project;
2. We can use absolute paths without any variables. Just use `Folder.current` and add `.rugby` subpath.

@blastmann What do you think about this? Any suggestions?

**Comment by swiftyfinch** [comment]
@blastmann Hey, could you try this fix?
```
mint install swiftyfinch/rugby@bugfix/absolute-paths
```

**Comment by blastmann** [comment]
> @blastmann Hey, could you try this fix?
> 
> ```
> mint install swiftyfinch/rugby@bugfix/absolute-paths
> ```

Yep, I just pick this up this morning, it seems adding another  variable like `$RUGBY_PATH` is a better solution.

**Comment by swiftyfinch** [comment]
OK, we are done with this 🚀 

You can use `main` branch right now. I'm going to release the new version a bit later.
```
mint install swiftyfinch/rugby@main
```
