### ISSUE TITLE
🔭 Command to Print Hashes of Current Configuration

### ISSUE THREAD

**Issue by VaslD** [swiftyfinch/Rugby#220]
## Is your feature request related to a problem? Please describe.

I have a Maven-like central server that stores built artifacts, and I'd like to somehow make it work with Rugby. I see that Rugby (as of 2.0 RC1) stores framework artifacts in `~/.rugby/bin` but the exact path requires a hash after framework name.

I ran `rugby build` twice on the same Git workspace and they generated two copies of the same framework under different hashes. I've guessed it was because I changed `xcode-select` toolchain but it still didn't help without knowing the exact rule to generate such hash.

## Describe the solution you'd like

Is it possible to make checksum calculation rules public?

## Describe alternatives you've considered

If the checksum is considered an implementation detail, can Rugby introduce new command that calculates the checksums of the current configuration/environment so a third-party tool can use these values to match caches on a remote server?

**Comment by VaslD** [comment]
Thanks for the pointers.

I looked into `rugby warmup`. While I do appreciate an all-in-one solution, `warmup` isn't exactly like what I had in mind.It seems `warmup` is a one-click integration with most object storage providers, e.g. AWS/GCP, etc. However, I'm hoping to plug `rugby warmup` into virtually any build pipeline and networked storage.

Say I have an NFS/FTP at home that holds last couple builds; or maybe a corporation already deploys Nexus or Travis. Rugby needs to tell others (A) what it needs, in case of `warmup`, and (B) what it generates, in case of `build`. Then the build pipeline can run its own way of retrieving built artifacts from previous sessions, and these steps may not be as simple as HTTP calls. After all, Rugby needs certain files at certain places but shouldn't care much about how they got there. 

I think I can work with `warmup` for now using a local server. It'd just be so much convenient if Rugby prints something like this (I don't know YAML too well so I'll use JSON for illustration):

```json
{
    "Alamofire": ["Debug", "iphonesimulator", "x86_64", "f38484a"]
}
```

Please consider adding this command.

**Comment by swiftyfinch** [comment]
@VaslD Thank a lot for sharing your thoughts!

I've already experimented with different solutions and tried to implement a more flexible one. There is an inconvenient way to achieve your needs. You can call such command and then grep logs `~/.rugby/logs`:
```
rugby warmup --analyse
```

You can see something like:
```
...
[19:42:34]:   ✓ Not Found:
- /Users/swiftyfinch/.rugby/bin/Alamofire/Debug-iphonesimulator-arm64/2aa7686
- /Users/swiftyfinch/.rugby/bin/AutoMate/Debug-iphonesimulator-arm64/ff8b6eb
- /Users/swiftyfinch/.rugby/bin/KeyboardLayoutGuide/Debug-iphonesimulator-arm64/f2e8b5d
- /Users/swiftyfinch/.rugby/bin/Kingfisher/Debug-iphonesimulator-arm64/a51a7c2
- /Users/swiftyfinch/.rugby/bin/LocalPod/Debug-iphonesimulator-arm64/d1891ee
- /Users/swiftyfinch/.rugby/bin/LocalPodResources/Debug-iphonesimulator-arm64/40ff11e
- /Users/swiftyfinch/.rugby/bin/Moya/Debug-iphonesimulator-arm64/79c1a62
- /Users/swiftyfinch/.rugby/bin/Rswift/Debug-iphonesimulator-arm64/c640851
- /Users/swiftyfinch/.rugby/bin/SnapKit/Debug-iphonesimulator-arm64/100e340
[19:42:34]:   ✓ Not Found Locally 100% Binaries (9/9)
...
```

Also, there is a file `~/.rugby/bin/+latest` which is created after each build process. There you can find paths to new binaries and upload it. Right now, I'm not going to add separate command for it, because it's not easy process even for AWS.

I did so when was integrating a remote cache for my work project. Then I added `warmup` command, because it's pretty easy for using a remote cache on local Macs. I agree that we need more convenient output format for parsing on CI. I've added this feature to roadmap and will think about it later.

Right now I'm thinking about `rugby warmup --analyse json` or something like this. Or maybe we can add `rugby warmup --analyse --output path/to/file.json`.

**Comment by VaslD** [comment]
Awesome! This is extremely helpful.

**Comment by swiftyfinch** [comment]
@VaslD Now you can read about 🐳 Remote Cache [here](https://github.com/swiftyfinch/Rugby/blob/2.0.0b7/docs/Remote%20Cache.md).
