### ISSUE TITLE
🐛 Broken Indexing

### ISSUE THREAD

**Issue by AkeyLaa** [swiftyfinch/Rugby#235]
## Describe the bug
After success rugby cache and succeed Xcode build - Indexing Xcode and live issues is Broken
Xcode use AppStore config and search moduleMap in dir Appstore - but working config is Development and cache is for Development

(By the way not upgrade for Rugby 2 cause same issues and project can not build)

Here is Indexing log (turns on "defaults write com.apple.dt.Xcode IDEIndexShowLog -bool YES" )
<img width="654" alt="Снимок экрана 2023-09-21 в 15 44 20" src="https://github.com/swiftyfinch/Rugby/assets/45689995/aa8b3a1a-9be1-4f41-b9d0-30e1f3490984">

**Comment by swiftyfinch** [comment]
Hello @AkeyLaa!

If I understand you correctly, you use the `Development` configuration in your Xcode project. Am I right?
The default configuration is `Debug` and Rugby also use it by default.

But you can pass a different configuration:
```sh
rugby --config Development
```
Check out docs for specific Rugby version for finding out more info.

**Comment by AkeyLaa** [comment]
> Hello @AkeyLaa!
> 
> If I understand you correctly, you use the `Development` configuration in your Xcode project. Am I right? The default configuration is `Debug` and Rugby also use it by default.
> 
> But you can pass a different configuration:
> 
> ```shell
> rugby --config Development
> ```
> 
> Check out docs for the specific Rugby version to find more information.

No, i use `rugby --config Development` in plan, and rugby working correct 
And after it Xcode build is succesed
But also in Xcode, Indexing is not working (which log i sent) - for example if i make a mistake in project, xcode won't show me live issue (project need AppStore build for show issues)

<img width="326" alt="Снимок экрана 2023-09-22 в 12 14 09" src="https://github.com/swiftyfinch/Rugby/assets/45689995/c9de97b9-0014-48ed-8fa1-88484ed42be7">

**Comment by swiftyfinch** [comment]
Oh, I see. If I understand you correctly, you expect that your source files in Xcode would be indexed.

But Rugby builds selected targets and then removes them from the project.
So, your source files don't attach to any target and aren't indexing as well.
I'm not sure how it works, but it's by design for Rugby.
It's a tool with some trade-offs. Unfortunately, you can't edit built binaries in Xcode and index/build them.

Right now, you can use options to exclude some targets from building process:
```sh
rugby -e MyPodToDevelopAndIndex
```

If you have some ideas on how to improve this, you are welcome here.
I'm going to open-source Rugby this weekend. But will see)

**Comment by swiftyfinch** [comment]
@AkeyLaa Hey, do you have any ideas?
I'm not sure about keeping this issue opened if we can't do anything.

**Comment by AkeyLaa** [comment]
> @AkeyLaa Hey, do you have any ideas? I'm not sure about keeping this issue opened if we can't do anything.

Yeah, go close.
Now, i have no idea to fix this
