### ISSUE TITLE
💬 How do I cache non-development pods?

### ISSUE THREAD

**Issue by dwade333** [swiftyfinch/Rugby#246]
## Is your feature request related to a problem? Please describe.
Due to the current component development, I need to develop through development pods. However, when I use rugby, it will cache all the pods containing development, which will cause the code I modified in the development pods to not take effect. So is there any command that can do it? What about caching non-development pods? If so, how should I deal with it?

## Describe the solution you'd like
With the current solution, I can only cache the content of development pods every time, which is inconvenient.

**Comment by swiftyfinch** [comment]
Hello @dwade333!

You can use these options to set a desired scope:
```sh
-t, --targets []           * Targets for building. Empty means all targets.
-g, --targets-as-regex []  * Targets for building as a RegEx pattern.
-e, --except []            * Exclude targets from building.
-x, --except-as-regex []   * Exclude targets from building as a RegEx pattern.
```
For example:
```sh
> rugby -e PodA PodB PodC
```

Also, you can do the same in `.rugby/plans.yml`:
```yml
dev:
- command: cache
  except:
  - PodA
  - PodB
  - PodC
```
And then call `rugby` without any options.

The `Rugby1.x` had an ability to cache only remote pods.
But it wasn't effective. It's better to cache development pods too, except some of them.

**Comment by dwade333** [comment]
For development pods, each time may be uncertain, it may only contain PodA, and sometimes it may only contain PodB, or it may contain multiple. 
Does the 2.x version of Rugby support the cache-only remote pod command? 
Thank you very much for your reply 🙏🏻

**Comment by swiftyfinch** [comment]
> For development pods, each time may be uncertain, it may only contain PodA, and sometimes it may only contain PodB, or it may contain multiple.

Yeah, but usually I work on the specific pods based on my task. And after that, I can change this scope to another. It allows me to focus on the narrow area. And it's better for performance in large projects.

> Does the 2.x version of Rugby support the cache-only remote pod command?

No, it hasn't. And I wasn't planning to add such ability to `Rugby2.x`.
There haven't been any requests yet.

---

Do you want to suggest an interface for such an option? Right now we can combine any of these:
```sh
-t, --targets []           * Targets for building. Empty means all targets.
-g, --targets-as-regex []  * Targets for building as a RegEx pattern.
-e, --except []            * Exclude targets from building.
-x, --except-as-regex []   * Exclude targets from building as a RegEx pattern.
```

I have an idea how to implement this feature, but.
Unfortunately, I don't have a clear design solution in my mind how to add an option to cache only remote pods.
And also, I want to know how many people need it) Because it will make the Rugby interface more complicated for everybody.

**Comment by swiftyfinch** [comment]
Hello! I've decided to close the issue, because there is not enough demand.

Feel free to reopen it if it's still important to you.
And let's collect more votes for this feature request.
