### ISSUE TITLE
💬 When a new pod is added to the Podfile, rugby does not cache it

### ISSUE THREAD

**Issue by Ernest0-Production** [swiftyfinch/Rugby#280]
## Did you already try Rugby doctor?

no (I forgot such a thing existed)

## Describe the bug

It looks like rugby uses a `.rugby/backup` folder, ignoring the possibility of new pod-targets appearing after they are added to the `Podfile` and the updated `Pods.xcodeproj` (after `pod install`)

## To Reproduce

Preparation:
- Podfile with some pods
- Generated Pods.xcodeproj and Pods/ after `pod install`
- Generated `.rubgy/` folder after `rugby cache`

Steps to reproduce behavior: 
- Add new pod in `Podfile` (for example `Alamofire`)
- Run `pod install`
- Run `rugby rollback; rugby cache`
- Open Xcode project and compile it

## Expected behavior

Success build

## Received behavior

No such module "Alamofire"

## Environment (please complete the following information):
 - Version 2.2.0

## Workaround

Remove `.rugby/` directory before each `rugby cache`

**Comment by cragod** [comment]
I have also encountered this issue because the rollback process restores the project to the state of the last backup before executing the cache, causing errors (missing the new pod).

My current workaround is, that after running `pod install`, the first `cache` does not include the `-r` flag. Starting from the second time, I use `cache -r` (which is equivalent to rugby rollback; rugby cache).

```
$ pod install
$ rugby cache ...
$ rugby cache ... -r
$ rugby cache ... -r
$ pod install
$ rugby cache ...
```

The `rollback` command might need to perform some comparisons to resolve this issue, but I think it a bit challenging. After the last backup, modifications were made to the pod project immediately, making it difficult to distinguish between changes caused by Rugby and those resulting from updates to the Podfile 🧐

**Comment by swiftyfinch** [comment]
@Ernest0-Production Hello! Thank you for this description.
It's by design. So, it's not a bug.

You can find information in the [docs/commands-help/rollback.md](https://github.com/swiftyfinch/Rugby/blob/main/Docs/commands-help/rollback.md#discussion).

> Your projects will be reset to state before the last Rugby use.

> Be careful, if you add some changes to your project after using Rugby, you lose them after calling `rollback`.
Use `pod install` instead of `rollback` in such cases.

And I agree with @cragod. You don't need to use `rugby rollback` after `pod install`.
```sh
> pod install
> rugby
```
If you don't make any changes in `Podfile`/`Pods.xcodeproj`, you can use `rugby rollback`:
```sh
> rugby --rollback # or -r

# It's equivalent
> rugby rollback && rugby
```

----

But I think that we can make an enchantment 🔭.
Rugby can keep a checksum of `Podfile.lock` in the backup folder.
And throw an error/warning if it's not equal to a checksum of the current `Podfile.lock`.
I'm not sure that we need this one.

**Comment by Ernest0-Production** [comment]
Thanks for the quick response! I forgot about this newance) 

It makes me think about **when a rollback might actually happen**. It looks like this is a more optimal way (in terms of speed) to disable the cache, compared to `pod install`. 
But at the same time, it has a nuance with the fact that a **backup is created only when the cache is connected(use) for the first time after pod install.** 

Hence the question arises: is such a command really needed? 
Perhaps there is a more unambiguous scenario when this command will be needed - I would be grateful for advice! 🙏

**Comment by swiftyfinch** [comment]
@Ernest0-Production I think the general answer is `rollback` could be much faster that `pod install`. `rollback` can take 2-3 seconds vs 2-3 minutes in case of `pod install` in a huge project (like mine one).

I checked this information also is presented in [docs](https://github.com/swiftyfinch/Rugby/blob/main/Docs/commands-help/rollback.md#discussion).

> 🏈 Rugby always must be used after `pod install` command ✅.
> But in huge projects, this command can take several minutes.

My scenarios:

Pull some changes from git:
```sh
> git pull # rebase/merge, etc.
> pod install
> rugby
```

Make some changes in `.rugby/plans.yml`:
```sh
> rugby -r
```
Or if you don't use plans you can do something like this:
```sh
> rugby -e AnotherTeamModule -r
```
And then work with integration to `AnotherTeamModule` in Xcode.
